logo: Home  # add logo name
title: Information Security Blog.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  Just a security blog for self notes and resources i use for learning I.T Security.It is intended to manage resources for bug hunting, red teaming,network pentesting.
permalink: ':title/'
baseurl: "/bef" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: homepage.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: author_kali.jpg # your photo
author-name: Saket Saurav #your name
about-author: A student and cyber security enthusiast.<br />I am an engineering student currently pursuing egineering in third year from Computer Science Department.<br />I have special interest in Network Pentesting , Red Teaming and Bug Hunting.<br /> I am a learner with  an ardent desire to learn more about cyber security. <br /> # about author
email: offseconhtb@gmail.com # your email
#Phone: +919602470565 
#Website: https://dwayne.example.com # you website

# Social link
#google_url:    # add url link
twitter_url:  https://twitter.com/SaketSourav14
instagram_url: https://www.instagram.com/saketsourav_111 # add url link
#interest_url: # add url link
#ribbble_url:  # add url link
#acebook_url:  # add url link

# Disqus
#discus_identifier: offsecin # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
#mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
